name: adelemaynes
favicon: null
layout_spectrum: 0.99749
typography_spectrum: 0.21898727910593152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#34122e'
    - '#c3a787'
    - '#444a50'
    - '#9c6156'
  brandStrength: 0.2341074706055224
  lightness: 0.8894194148015231
  saturation: 0.023879725951701403
  rhythmicContrast: 0.5260736767668277
purpose: []
