name: adelemaynes
favicon: null
layout_spectrum: 0.16308577870950103
typography_spectrum: 0.21898727910593152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2341074706055224
  lightness: 0.8894194148015231
  saturation: 0.023879725951701403
  rhythmicContrast: 0.5260736767668277
purpose: []
